export enum Wick {
    Wooden = 'WOOD',
    Cotton = 'COTTON'
}

export enum Colors {
    White = 'WHITE',
    Black = 'BLACK',
    Transparent = 'TRANSPARENT',
}

export enum Aroma {
    SweetOrangeSriracha= 'Sweet Orange Sriracha',
    Fireside = 'Fireside',
    CaribbeanTeakwood = 'Caribbean teakwood',
    BeachLinen = 'Beach linen',
    Hepm = 'Hepm',
    ButterscotchBourbon = 'Butterscotch & Bourbon',
    HanselAndGretelsHouse = "Hansel and gretel's house",
    ChocolateFudge = 'Chocolate Fudge',
    SparklingGrapefruit = 'Sparkling grapefruit',
    Library = 'Library',
    CampfireMarshmallows = 'Campfire marshmallows',
    PumpkinSpiceButtercream = 'Pumpkin spice buttercream',
    FallenLeaves = 'Fallen leaves',
    Lily = 'Lily',
    RoseAndOud = 'Rose and Oud',
    BlackRaspberryVanilla = 'Black raspberry vanilla',
    OceanBreeze = 'Ocean breeze',
    Wassail = 'Wassail',
    HighTide = 'High tide',
    NordicNight = 'Nordic night',
    BlackCurrantAbsinthe = 'Black currant absinthe',
    Cotton = 'Cotton',
    Vanilla = 'Vanilla',
    Sangria = 'Sangria',
    WhiteOakAndVanilla = 'White oak and vanilla',
    NagChampa = 'Nag champa',
    SweetTobacco = 'Sweet tobacco',
    Garden = 'Garden',
    CremeBrulee = 'Creme brulee',
    StrawberriesAndCream = 'Strawberries and cream',
    Petrichor = 'Petrichor',
    MountainMist = 'Mountain mist',
    SmokedOud = 'Smoked Oud',
    JamaicaMeCrazy = 'Jamaica me crazy',
    MovieTheaterPopcorn = 'Movie Theater Popcorn',
    OliveLeafAndCitron = 'Olive Leaf and Citron',
    PinkSugarCrystals = 'Pink Sugar Crystals',
    LemonVerbena = 'Lemon Verbena',
    EgyptianAmber = 'Egyptian Amber',
    DryGinAndCypress = 'Dry Gin and Cypress',
    ApplewoodFirNeedle = 'Applewood Fir Needle',
    ToastedPumpkinSpice = 'Toasted Pumpkin Spice',
    CoffeeShop = 'Coffee shop',
    FreshlyBakedBread = 'Freshly baked bread',
    BlueberryPie = 'Blueberry pie',
    VanillaEggnog = 'Vanilla eggnog',
    ApplePie = 'Apple pie',
    OatmealMilkNHoney = 'Oatmeal Milk-n-Honey',
    BalsamAndEdar = 'Balsam and Cedar',
    MountainPine = 'Mountain Pine',
    VanillaCaramel = 'Vanilla Caramel',
    SugaredChestnuts = 'Sugared Chestnuts',
    FraserFir = 'Fraser Fir',
    CocoaButterCashmere = 'Cocoa Butter Cashmere',
    BlueberryCobbler = 'Blueberry cobbler',
    FreshCoffee = 'Fresh coffee',
    WholeWheatBread = 'Whole wheat bread',
    OakmossAndAmber = 'Oakmoss and amber',
    WatermintAndClementine = 'Watermint and clementine',
    PaloSantoPatchouli = 'Palo santo patchouli',
    CinnamonDoughnuts = 'Cinnamon doughnuts',
    TonkaAndOud = 'Tonka and Oud',
    CaramelPopcorn = 'Caramel popcorn',
    SugarPlumPunch = 'Sugar plum punch',
    FreshCutGrass = 'Fresh cut grass',
    CrystallisedGingerAndCardamom = 'Crystallised ginger and cardamom',
    GrapefruitAndMint = 'Grapefruit and mint',
    ChristmasMemories = 'Christmas memories',
    ChristmasHearth = 'Christmas hearth',
    VelvetVanilla = 'Velvet vanilla',

}